name: gorilla-roxo-cloud-stack

services:
  caddy:
    image: caddy:2.9.1-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019"
    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./config/caddy/site:/srv
      - ./.docker_volume/caddy/data:/data
      - ./.docker_volume/caddy/config:/config
    networks:
      - gorilla-roxo-cloud-network

  uptime-kuma:
    image: louislam/uptime-kuma:1.23.16
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./.docker_volume/uptime-kuma:/app/data
    ports:
      - "3001:3001"
    networks:
      - gorilla-roxo-cloud-network

  ntfy:
    image: binwiederhier/ntfy:v2.11.0
    container_name: ntfy
    command:
      - serve
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ./.docker_volume/ntfy:/var/lib/ntfy
      - ./config/ntfy/server.yml:/etc/ntfy/server.yml
    ports:
      - "8080:80"
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - gorilla-roxo-cloud-network

networks:
  gorilla-roxo-cloud-network:
    external: true
